#!/usr/bin/python3

# Copyright (c) 2017, 2020 Samuel Thibault <samuel.thibault@ens-lyon.org>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY Samuel Thibault ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

import sys
import pygame
import io
import socket

# Screen setup

width = 1280
height = 720

ball_speed = [ -20, -20 ]
racket_speed = [ 0, 0 ]
racket2_speed = [ 0, 0 ]

score1 = 0
score2 = 0

serveur = None

# Ouverture du fichier
if len(sys.argv) >= 2:
    serveur = False
    print(sys.argv[1])
    try:
        c = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
        c.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        c.connect((sys.argv[1], 7777))
    except Exception as e:
        print("socket error:", e)
        sys.exit(1)
else:
    serveur = True
    try:
        s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, 0)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind(('', 7777))
        s.listen(1)
        s2, addr = s.accept() # fonction bloquante
    except Exception as e:
        print("socket error:", e)
        sys.exit(1)

# Pygame initialization
pygame.init()
screen = pygame.display.set_mode( (width, height) )
if serveur :
    pygame.display.set_caption('Serveur')
else :
    pygame.display.set_caption('Client')

myfont = pygame.font.SysFont(None, 75)


# Load resources
court = pygame.image.load("image/court.png")

ball = pygame.image.load("image/ball.png")
ball_coords = ball.get_rect()

racket = pygame.image.load("image/racket.png")
racket_coords = racket.get_rect()

racket2 = pygame.image.load("image/racket.png")
racket2_coords = racket2.get_rect()

# Throw ball from center
def throw():
    ball_coords.left = 2*width/3
    ball_coords.top = height/2

throw()

while True:
    for e in pygame.event.get():
        # Check for exit
        if e.type == pygame.QUIT:
            sys.exit()

        # Check for racket movements
        elif e.type == pygame.KEYDOWN:
            if e.key == pygame.K_UP:
                if serveur :
                    racket_speed[1] = -15
                else :
                    racket2_speed[1] = -15
                pass
            elif e.key == pygame.K_DOWN:
                if serveur :
                    racket_speed[1] = 15
                else :
                    racket2_speed[1] = 15
                pass

        elif e.type == pygame.KEYUP:
            if e.key == pygame.K_UP:
                if serveur :
                    racket_speed[1] = 0
                else :
                    racket2_speed[1] = 0
                pass
            elif e.key == pygame.K_DOWN:
                if serveur :
                    racket_speed[1] = 0
                else :
                    racket2_speed[1] = 0
                pass
        

    if serveur :
        # Move ball
        ball_coords = ball_coords.move(ball_speed)
        # Bounce ball on walls
        if ball_coords.left < 0 or ball_coords.right >= width:
            ball_speed[0] = -ball_speed[0]
        if ball_coords.top < 0 or ball_coords.bottom >= height:
            ball_speed[1] = -ball_speed[1]

    if serveur :
        # Move racket
        racket_coords = racket_coords.move(racket_speed)
    else :
        # Move racket2
        racket2_coords = racket2_coords.move(racket2_speed)

    # Clip racket on court
    if racket_coords.left < 0:
        racket_coords.left = 0
    elif racket_coords.right >= width:
        racket_coords.right = width-1
    if racket_coords.top < 0:
        racket_coords.top = 0
    elif racket_coords.bottom >= height:
        racket_coords.bottom = height-1

    # Clip racket2 on court
    if racket2_coords.left < width-37:
        racket2_coords.left = width-37
    elif racket2_coords.right > width:
        racket2_coords.right = width
    if racket2_coords.top < 0:
        racket2_coords.top = 0
    elif racket2_coords.bottom >= height:
        racket2_coords.bottom = height-1

    #socket
    if serveur:
        #emission
        reply =  str(ball_coords.left) + ' ' + str(ball_coords.right) + ' ' + str(ball_coords.top) + ' ' + str(ball_coords.bottom) + ' ' + str(racket_coords.left) + ' ' + str(racket_coords.right) + ' ' + str(racket_coords.top) + ' ' + str(racket_coords.bottom)
        s2.send(reply.encode())


        #reception
        data = s2.recv(1500)
        decode = data.decode("utf-8")

        pos_racket2 = decode.split(" ")

        racket2_coords.left = int(pos_racket2[0])
        racket2_coords.right = int(pos_racket2[1])
        racket2_coords.top = int(pos_racket2[2])
        racket2_coords.bottom = int(pos_racket2[3])

        if data == b'':
            break
            s2.close()
        
    #client      
    else:
        #emission
        reply = str(racket2_coords.left) + ' ' + str(racket2_coords.right) + ' ' + str(racket2_coords.top) + ' ' + str(racket2_coords.bottom)
        c.send(reply.encode())

        #reception
        data = c.recv(1500)
        decode = data.decode("utf-8")

        positions = decode.split(" ")

        ball_coords.left = int(positions[0])
        ball_coords.right = int(positions[1])
        ball_coords.top = int(positions[2])
        ball_coords.bottom = int(positions[3])

        racket_coords.left = int(positions[4])
        racket_coords.right = int(positions[5])
        racket_coords.top = int(positions[6])
        racket_coords.bottom = int(positions[7])

        if data == b'':
            break
            c.close()  


    # Racket reached racket position?
    if ball_coords.left <= 0:
        if ball_coords.bottom <= racket_coords.top or ball_coords.top >= racket_coords.bottom:
            if serveur :
                print("lost!")
            else:
                print("win!")
            score2 += 1
            throw()

    if ball_coords.right >= width:
        if ball_coords.bottom <= racket2_coords.top or ball_coords.top >= racket2_coords.bottom:
            if serveur :
                print("win!")
            else:
                print("lost!")
            score1 += 1
            throw()

    textsurface = myfont.render(str(score1) + ' | ' + str(score2), True, (0, 0, 0))
    text_coords = textsurface.get_rect()
    text_coords.left = width/2 - text_coords.width/2
    text_coords.top = 10

    # Display everything
    screen.blit(court, (0,0))
    screen.blit(ball, ball_coords)
    screen.blit(racket, racket_coords)
    screen.blit(racket2, racket2_coords)
    screen.blit(textsurface, text_coords)
    pygame.display.flip()

    # sleep 10ms, since there is no need for more than 100Hz refresh :)
    pygame.time.delay(10)